export { default as PostsPage } from './PostsPage'
export { default as HomePage } from './HomePage'
export { default as MyPage } from './MyPage'
// export { default as LoginPage } from './LoginPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as SignInPage } from './SignInPage'
export { default as SignUpPage } from './SignUpPage'
